name: paddel
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - api
      - web
  
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    container_name: api

  web:
    build: ./web
    container_name: web