version: "3.9"
name: paddel
services:
  proxy:
    container_name: proxy
    env_file:
      - .env
    build: ./proxy
    ports:
      - ${PUBLIC_HTTP_PORT}:80
      - ${PUBLIC_HTTPS_PORT}:443
    volumes:
      - ./data/proxy:/data
    depends_on:
      - api
      - web

  api:
    container_name: api
    env_file:
      - .env
    build:
      context: ../
      dockerfile: ./app/api/Dockerfile

  web:
    container_name: web
    env_file:
      - .env
    build: ./web
