services:
  api:
    build:
      target: development
    volumes:
      - ../paddel:/code/paddel
      - ./api/app:/code/app

  web:
    build:
      target: development
    volumes:
      - ./web:/code
      - /code/node_modules
      - /code/.next
