version: "3.9"
name: paddel
services:
  proxy:
    container_name: proxy
    build: ./proxy
    environment:
      - WEB_LOCATION=${WEB_LOCATION}
      - API_LOCATION=${API_LOCATION}
    ports:
      - ${APP_PORT}:443
    volumes:
      - ./data/proxy:/data
    depends_on:
      - api
      - web

  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./app/api/Dockerfile

  web:
    container_name: web
    build: ./web
    environment:
      - NEXT_PUBLIC_API_LOCATION=${API_LOCATION}
