version: "3.9"
name: paddel
services:
  proxy:
    container_name: proxy
    build: ./proxy
    environment:
      - WEB_LOCATION=${WEB_LOCATION}
      - API_LOCATION=${API_LOCATION}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./data/proxy:/data
    depends_on:
      - api
      - web

  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./app/api/Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./data/api:/data
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: web
    build: ./web
    environment:
      - NEXT_PUBLIC_API_LOCATION=${API_LOCATION}

  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/data
    volumes:
      - ./data/db:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
