version: "3.9"
name: paddel
services:
  proxy:
    container_name: proxy
    build: ./proxy
    environment:
      - WEB_URL=${WEB_URL}
      - API_URL=${API_URL}
      - WEB_PATH=${WEB_PATH}
      - API_PATH=${API_PATH}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./data/proxy:/data
    depends_on:
      - api
      - web

  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./app/api/Dockerfile
    environment:
      - API_PATH=${API_PATH}

  web:
    container_name: web
    build: ./web
