services:
  proxy:
    build:
      target: development

  api:
    build:
      target: development
    volumes:
      - ./api:/api
      - ../paddel:/paddel

  web:
    build:
      target: development
    volumes:
      - ./web:/web
      - /web/node_modules