[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "paddel"
version = "0.0.2"
requires-python = "~=3.9"
dependencies = [
    "opencv-python~=4.7.0.68",
    "numpy~=1.24.1",
    "scikit-learn~=1.2.1",
    "mediapipe~=0.9.0.1",
    "pydantic~=1.10.4",
]

[project.optional-dependencies]
dev = [
    "pytest~=7.2.1",
    "pytest-cov~=4.0.0",
    "mypy~=0.991",
    "black~=22.12.0",
    "isort~=5.12.0",
]

[tool.coverage.run]
parallel = true
source = ["src"]

[tool.mypy]
strict = true

[tool.black]
target-version = ['py39']

[tool.isort]
profile = "black"